### ISSUE TITLE
TypeError: DiT.forward() got an unexpected keyword argument 'cond_drop'

### ISSUE THREAD

**Issue by banhongjun** [DakeQQ/F5-TTS-ONNX#15]
麻烦大佬解答下这个问题：
Traceback (most recent call last):
  File "/root/ban/F5-TTS-main_20241223/F5-TTS-ONNX-main/Export_ONNX/F5_TTS/Export_F5.py", line 330, in <module>
    torch.onnx.export(
  File "/root/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/root/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/onnx/utils.py", line 1612, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/root/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/onnx/utils.py", line 1134, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/root/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/onnx/utils.py", line 1010, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/root/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/onnx/utils.py", line 914, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/root/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/jit/_trace.py", line 1310, in _get_trace_graph
    outs = ONNXTracedModule(
  File "/root/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/jit/_trace.py", line 138, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/root/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/jit/_trace.py", line 129, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/root/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1522, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/root/ban/F5-TTS-main_20241223/F5-TTS-ONNX-main/Export_ONNX/F5_TTS/Export_F5.py", line 168, in forward
    pred = self.f5_transformer(x=noise, cond=cat_mel_text, cond_drop=cat_mel_text_drop, time=self.time_expand[:, time_step], rope_cos=rope_cos, rope_sin=rope_sin, qk_rotated_empty=qk_rotated_empty)
  File "/root/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1522, in _slow_forward
    result = self.forward(*input, **kwargs)
TypeError: DiT.forward() got an unexpected keyword argument 'cond_drop'

**Comment by DakeQQ** [comment]
错误 `DiT.forward() got an unexpected keyword argument 'cond_drop'` 是由于使用 `shutil.copyfile()` 时复制过程不完整导致的。  

以下是复制脚本：  
```python
shutil.copyfile(modified_path + '/vocos/heads.py', python_package_path + '/vocos/heads.py')
shutil.copyfile(modified_path + '/vocos/models.py', python_package_path + '/vocos/models.py')
shutil.copyfile(modified_path + '/vocos/modules.py', python_package_path + '/vocos/modules.py')
shutil.copyfile(modified_path + '/vocos/pretrained.py', python_package_path + '/vocos/pretrained.py')
shutil.copyfile(modified_path + '/F5/modules.py', F5_project_path + '/f5_tts/model/modules.py')
shutil.copyfile(modified_path + '/F5/dit.py', F5_project_path + '/f5_tts/model/backbones/dit.py')
shutil.copyfile(modified_path + '/F5/utils_infer.py', F5_project_path + '/f5_tts/infer/utils_infer.py')
```

有时，由于磁盘延迟，复制过程可能无法完全完成。如果发生这种情况，请点击“RUN”并重新运行脚本。  

我们刚刚测试过，如果复制过程正常完成，则 ONNX 模型应能成功导出。

**Comment by jasonzhang761213** [comment]
我也碰到同样的问题，在ssd上执行，错误解决不了

**Comment by DakeQQ** [comment]
我们刚刚再次确认了导出脚本，是可以顺利导出的：）

如果错误持续发生，可以尝试以下步骤:

1. 重新启动编辑器，並再次执行脚本。如果仍发生错误，则前往步骤2。
2. 重新启动电脑，並再次执行脚本。如果仍发生错误，则前往步骤3。
3. 添加修改权限，並再次执行脚本。
 - Linux: `sudo chmod 777 -R python_package_path`
 - Windows: 前往文件夾`python_package_path`
     - 右键 -> `属性`
     - `安全`的标签页
     - 点击当前的用户名后，点选`编辑`
     - 句选`完全控制`
     - 点击`确定`并退出


如果以上都无法解决，则需要將modeling_modified中的文件，**手动复制并替换对应位置的Python文件**。（修改文件多，还请您耐心操作）

**Comment by tharyckgusmao** [comment]
It worked for me, debug to see where your f5 files are and you.

print(f5_tts.model.__file__)
